name: 'REPORT'
on: 
  workflow_run:
    workflows: ['TEST']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: back-report               # Set ID reference for step
        with:
          name: Back-End Tests            # Name of the check run which will be created
          artifact: back-results
          path: '*.xml'
          reporter: java-junit        # Format of test results

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: front-report               # Set ID reference for step
        with:
          name: Back-End Tests            # Name of the check run which will be created
          artifact: front-results
          path: '*.xml'
          reporter: jest-junit        # Format of test results
