name: 'REPORT'
on: 
  workflow_run:
    workflows: ['TEST']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Back End Test Report
        uses: dorny/test-reporter@v2
        id: back-report
        with:
          name: Back-End Tests
          artifact: back-results
          path: '*.xml'
          reporter: java-junit

      - name: Front End Test Report
        uses: dorny/test-reporter@v2
        id: front-report
        with:
          name: Back-End Tests
          artifact: front-results
          path: '*.xml'
          reporter: java-junit
